def bankdb():
    data = [
        {
            "bank_code": "090116",
            "cbn_code": "993",
            "name": "AMML MFB",
            "bank_short_name": "amml-mfb",
            "ussd_code": "",
            "logo": "https://nigeria-banks.onrender.com/static/images/amml-mfb.png",
        },
        {
            "bank_code": "070010",
            "cbn_code": "801",
            "name": "Abbey Mortgage Bank",
            "bank_short_name": "abbey-mortgage-bank",
            "ussd_code": "*332#",
            "logo": "https://nigeria-banks.onrender.com/static/images/abbey-mortgage-bank.png",
        },
        {
            "bank_code": "090260",
            "cbn_code": "51204",
            "name": "Above Only MFB",
            "bank_short_name": "above-only-mfb",
            "ussd_code": "",
            "logo": "https://nigeria-banks.onrender.com/static/images/above-only-mfb.png",
        },
        {
            "bank_code": "090197",
            "cbn_code": "606",
            "name": "Abu MFB",
            "bank_short_name": "abu_mfb",
            "ussd_code": "",
            "logo": "https://nigeria-banks.onrender.com/static/images/abu_mfb.png",
        },
        {
            "bank_code": "090270",
            "cbn_code": "613",
            "name": "Ab MFB",
            "bank_short_name": "ab-mfb",
            "ussd_code": "*389*755#",
            "logo": "https://nigeria-banks.onrender.com/static/images/ab-mfb.png",
        },
        {
            "bank_code": "000014",
            "cbn_code": "063",
            "name": "Access Bank Nigeria",
            "bank_short_name": "access",
            "ussd_code": "*901#",
            "logo": "https://nigeria-banks.onrender.com/static/images/access.png",
        },
        {
            "bank_code": "100052",
            "cbn_code": "052",
            "name": "Access Yello and Beta",
            "bank_short_name": "access-yello-beta",
            "ussd_code": "*901#",
            "logo": "https://nigeria-banks.onrender.com/static/images/access-yello-beta.png",
        },
        {
            "bank_code": "100013",
            "cbn_code": "323",
            "name": "Accessmoney",
            "bank_short_name": "access-mobile",
            "ussd_code": "*901#",
            "logo": "https://nigeria-banks.onrender.com/static/images/access-mobile.png",
        },
        {
            "bank_code": "090134",
            "cbn_code": "602",
            "name": "Accion MFB",
            "bank_short_name": "accion-mfb",
            "ussd_code": "*572#",
            "logo": "https://nigeria-banks.onrender.com/static/images/accion-mfb.png",
        },
        {
            "bank_code": "090160",
            "cbn_code": "975",
            "name": "Addosser MFB",
            "bank_short_name": "addosser-mfb",
            "ussd_code": "*258#",
            "logo": "https://nigeria-banks.onrender.com/static/images/addosser-mfb.png",
        },
        {
            "bank_code": "090268",
            "cbn_code": "618",
            "name": "Adeyemi College Staff MFB",
            "bank_short_name": "adeyemi-college-staff-mfb",
            "ussd_code": "",
            "logo": "https://nigeria-banks.onrender.com/static/images/adeyemi-college-staff-mfb.png",
        },
        {
            "bank_code": "100028",
            "cbn_code": "028",
            "name": "Ag Mortgage Bank",
            "bank_short_name": "ag-mortgage-bank",
            "ussd_code": "",
            "logo": "https://nigeria-banks.onrender.com/static/images/ag-mortgage-bank.png",
        },
        {
            "bank_code": "090277",
            "cbn_code": "51076",
            "name": "Al-Hayat MFB",
            "bank_short_name": "al-hayat-mfb",
            "ussd_code": "",
            "logo": "https://nigeria-banks.onrender.com/static/images/al-hayat-mfb.png",
        },
        {
            "bank_code": "090259",
            "cbn_code": "608",
            "name": "Alekun MFB",
            "bank_short_name": "alekun-mfb",
            "ussd_code": "",
            "logo": "https://nigeria-banks.onrender.com/static/images/alekun-mfb.png",
        },
        {
            "bank_code": "090297",
            "cbn_code": "642",
            "name": "Alert MFB",
            "bank_short_name": "alert-mfb",
            "ussd_code": "",
            "logo": "https://nigeria-banks.onrender.com/static/images/alert-mfb.png",
        },
        {
            "bank_code": "090131",
            "cbn_code": "040",
            "name": "Allworkers MFB",
            "bank_short_name": "allworkers-mfb",
            "ussd_code": "",
            "logo": "https://nigeria-banks.onrender.com/static/images/allworkers-mfb.png",
        },
        {
            "bank_code": "090169",
            "cbn_code": "584",
            "name": "Alpha Kapital MFB",
            "bank_short_name": "alpha-mfb",
            "ussd_code": "https://nigeria-banks.onrender.com/static/images/alpha-mfb.jpg",
            "logo": "",
        },
        {
            "bank_code": "090180",
            "cbn_code": "50926",
            "name": "Amju Unique MFB",
            "bank_short_name": "amju-mfb",
            "ussd_code": "",
            "logo": "https://nigeria-banks.onrender.com/static/images/amju-mfb.png",
        },
        {
            "bank_code": "090143",
            "cbn_code": "986",
            "name": "Apeks MFB",
            "bank_short_name": "apeks-mfb",
            "ussd_code": "",
            "logo": "https://nigeria-banks.onrender.com/static/images/apeks-mfb.png",
        },
        {
            "bank_code": "090001",
            "cbn_code": "401",
            "name": "Aso Savings And Loans",
            "bank_short_name": "aso-savings",
            "ussd_code": "",
            "logo": "https://nigeria-banks.onrender.com/static/images/aso-savings.png",
        },
        {
            "bank_code": "090172",
            "cbn_code": "631",
            "name": "Astrapolaris MFB",
            "bank_short_name": "astrapolaris-mfb",
            "ussd_code": "",
            "logo": "https://nigeria-banks.onrender.com/static/images/astrapolaris-mfb.png",
        },
        {
            "bank_code": "090264",
            "cbn_code": "612",
            "name": "Auchi MFB",
            "bank_short_name": "auchi-mfb",
            "ussd_code": "",
            "logo": "https://nigeria-banks.onrender.com/static/images/auchi-mfb.png",
        },
        {
            "bank_code": "090127",
            "cbn_code": "037",
            "name": "BC Kash MFB",
            "bank_short_name": "bc-kash-mfb",
            "ussd_code": "",
            "logo": "https://nigeria-banks.onrender.com/static/images/bc-kash-mfb.png",
        },
        {
            "bank_code": "090188",
            "cbn_code": "593",
            "name": "Baines Credit MFB",
            "bank_short_name": "baines-mfb",
            "ussd_code": "",
            "logo": "https://nigeria-banks.onrender.com/static/images/baines-mfb.png",
        },
        {
            "bank_code": "090326",
            "cbn_code": "647",
            "name": "Balogun Gambari MFB",
            "bank_short_name": "balogun-mfb",
            "ussd_code": "",
            "logo": "https://nigeria-banks.onrender.com/static/images/balogun-mfb.jpg",
        },
        {
            "bank_code": "090136",
            "cbn_code": "577",
            "name": "Baobab MFB",
            "bank_short_name": "baobab-mfb",
            "ussd_code": "",
            "logo": "https://nigeria-banks.onrender.com/static/images/baobab-mfb.png",
        },
        {
            "bank_code": "090117",
            "cbn_code": "581",
            "name": "Boctrust MFB",
            "bank_short_name": "",
            "ussd_code": "",
            "logo": "",
        },
        {
            "bank_code": "090176",
            "cbn_code": "",
            "name": "Bosak MFB",
            "bank_short_name": "",
            "ussd_code": "",
            "logo": "",
        },
        {
            "bank_code": "090148",
            "cbn_code": "50931",
            "name": "Bowen MFB",
            "bank_short_name": "",
            "ussd_code": "",
            "logo": "",
        },
        {
            "bank_code": "070015",
            "cbn_code": "",
            "name": "Brent Mortgage Bank",
            "bank_short_name": "",
            "ussd_code": "",
            "logo": "",
        },
        {
            "bank_code": "090293",
            "cbn_code": "",
            "name": "Brethren MFB",
            "bank_short_name": "",
            "ussd_code": "",
            "logo": "",
        },
        {
            "bank_code": "090308",
            "cbn_code": "",
            "name": "Brightway MFB",
            "bank_short_name": "",
            "ussd_code": "",
            "logo": "",
        },
        {
            "bank_code": "",
            "cbn_code": "865",
            "name": "CASHCONNECT MFB",
            "bank_short_name": "cashconnect-mfb-ng",
            "ussd_code": "",
            "bank_logo": "",
        },
        {
            "bank_code": "090154",
            "cbn_code": "50823",
            "name": "CEMCS MFB",
            "bank_short_name": "cemcs",
            "ussd_code": "",
            "logo": "https://nigeria-banks.onrender.com/static/images/cemcs.png",
        },
        {
            "bank_code": "090144",
            "cbn_code": "",
            "name": "CIT MFB",
            "bank_short_name": "",
            "ussd_code": "",
            "logo": "",
        },
        {
            "bank_code": "100005",
            "cbn_code": "",
            "name": "Cellulant",
            "bank_short_name": "",
            "ussd_code": "",
            "logo": "",
        },
        {
            "bank_code": "",
            "cbn_code": "50171",
            "name": "Chanelle Microfinance Bank Limited",
            "bank_short_name": "chanelle-microfinance-bank-limited-ng",
            "ussd_code": "",
            "bank_logo": "",
        },
        {
            "bank_code": "090141",
            "cbn_code": "",
            "name": "Chikum MFB",
            "bank_short_name": "",
            "ussd_code": "",
            "logo": "",
        },
        {
            "bank_code": "000009",
            "cbn_code": "023",
            "name": "Citibank Nigeria",
            "bank_short_name": "citibankng",
            "ussd_code": "",
            "logo": "https://nigeria-banks.onrender.com/static/images/citibankng.png",
        },
        {
            "bank_code": "090130",
            "cbn_code": "50910",
            "name": "Consumer MFB",
            "bank_short_name": "",
            "ussd_code": "",
            "logo": "",
        },
        {
            "bank_code": "100032",
            "cbn_code": "",
            "name": "Contec Global Infotech",
            "bank_short_name": "",
            "ussd_code": "",
            "logo": "",
        },
        {
            "bank_code": "",
            "cbn_code": "50204",
            "name": "Corestep MFB",
            "bank_short_name": "corestep-mfb",
            "ussd_code": "",
            "bank_logo": "",
        },
        {
            "bank_code": "060001",
            "cbn_code": "060001",
            "name": "Coronation Merchant Bank",
            "bank_short_name": "cmfb",
            "ussd_code": "",
            "logo": "",
        },
        {
            "bank_code": "070006",
            "cbn_code": "",
            "name": "Covenant",
            "bank_short_name": "",
            "ussd_code": "",
            "logo": "",
        },
        {
            "bank_code": "090159",
            "cbn_code": "",
            "name": "Credit Afrique MFB",
            "bank_short_name": "",
            "ussd_code": "",
            "logo": "",
        },
        {
            "bank_code": "",
            "cbn_code": "51297",
            "name": "Crescent MFB",
            "bank_short_name": "crescent-mfb",
            "ussd_code": "",
            "bank_logo": "",
        },
        {
            "bank_code": "090167",
            "cbn_code": "",
            "name": "Daylight MFB",
            "bank_short_name": "",
            "ussd_code": "",
            "logo": "",
        },
        {
            "bank_code": "",
            "cbn_code": "50162",
            "name": "Dot Microfinance Bank",
            "bank_short_name": "dot-microfinance-bank-ng",
            "ussd_code": "",
            "bank_logo": "",
        },
        {
            "bank_code": "090156",
            "cbn_code": "",
            "name": "E-Barcs MFB",
            "bank_short_name": "",
            "ussd_code": "",
            "logo": "",
        },
        {
            "bank_code": "090294",
            "cbn_code": "",
            "name": "Eagle Flight MFB",
            "bank_short_name": "",
            "ussd_code": "",
            "logo": "",
        },
        {
            "bank_code": "100021",
            "cbn_code": "",
            "name": "Eartholeum (Qik Qik)",
            "bank_short_name": "",
            "ussd_code": "",
            "logo": "",
        },
        {
            "bank_code": "000010",
            "cbn_code": "050",
            "name": "Ecobank Bank",
            "bank_short_name": "ecobank",
            "ussd_code": "*326#",
            "logo": "https://nigeria-banks.onrender.com/static/images/ecobank.png",
        },
        {
            "bank_code": "100008",
            "cbn_code": "307",
            "name": "Ecobank Xpress",
            "bank_short_name": "ecobank-mobile",
            "ussd_code": "",
            "logo": "",
        },
        {
            "bank_code": "090310",
            "cbn_code": "",
            "name": "EdFin MFB",
            "bank_short_name": "",
            "ussd_code": "",
            "logo": "",
        },
        {
            "bank_code": "",
            "cbn_code": "50263",
            "name": "Ekimogun MFB",
            "bank_short_name": "ekimogun-mfb-ng",
            "ussd_code": "",
            "bank_logo": "",
        },
        {
            "bank_code": "090097",
            "cbn_code": "098",
            "name": "Ekondo MFB",
            "bank_short_name": "ekondo",
            "ussd_code": "*540*178#",
            "logo": "https://nigeria-banks.onrender.com/static/images/ekondo.png",
        },
        {
            "bank_code": "090273",
            "cbn_code": "",
            "name": "Emeralds MFB",
            "bank_short_name": "",
            "ussd_code": "",
            "logo": "",
        },
        {
            "bank_code": "090114",
            "cbn_code": "",
            "name": "Empire Trust MFB",
            "bank_short_name": "",
            "ussd_code": "",
            "logo": "",
        },
        {
            "bank_code": "090189",
            "cbn_code": "",
            "name": "Esan MFB",
            "bank_short_name": "",
            "ussd_code": "",
            "logo": "",
        },
        {
            "bank_code": "090166",
            "cbn_code": "",
            "name": "Eso-E MFB",
            "bank_short_name": "",
            "ussd_code": "",
            "logo": "",
        },
        {
            "bank_code": "100006",
            "cbn_code": "",
            "name": "Etranzact",
            "bank_short_name": "",
            "ussd_code": "",
            "logo": "",
        },
        {
            "bank_code": "090304",
            "cbn_code": "",
            "name": "Evangel MFB",
            "bank_short_name": "",
            "ussd_code": "",
            "logo": "",
        },
        {
            "bank_code": "",
            "cbn_code": "50126",
            "name": "Eyowo",
            "bank_short_name": "eyowo",
            "ussd_code": "",
            "bank_logo": "",
        },
        {
            "bank_code": "060002",
            "cbn_code": "911",
            "name": "FBNQuest Merchant Bank",
            "bank_short_name": "",
            "ussd_code": "",
            "logo": "",
        },
        {
            "bank_code": "100031",
            "cbn_code": "",
            "name": "FCMB Easy Account",
            "bank_short_name": "",
            "ussd_code": "",
            "logo": "",
        },
        {
            "bank_code": "090290",
            "cbn_code": "",
            "name": "FCT MFB",
            "bank_short_name": "",
            "ussd_code": "",
            "logo": "",
        },
        {
            "bank_code": "100001",
            "cbn_code": "",
            "name": "FETS (My Wallet)",
            "bank_short_name": "",
            "ussd_code": "",
            "logo": "",
        },
        {
            "bank_code": "090153",
            "cbn_code": "",
            "name": "FFS Microfinance",
            "bank_short_name": "",
            "ussd_code": "",
            "logo": "",
        },
        {
            "bank_code": "",
            "cbn_code": "50315",
            "name": "FLOURISH MFB",
            "bank_short_name": "flourish-mfb-ng",
            "ussd_code": "",
            "bank_logo": "",
        },
        {
            "bank_code": "400001",
            "cbn_code": "501",
            "name": "FSDH Merchant Bank",
            "bank_short_name": "fsdh",
            "ussd_code": "",
            "logo": "",
        },
        {
            "bank_code": "",
            "cbn_code": "51318",
            "name": "Fairmoney Microfinance Bank",
            "bank_short_name": "fairmoney-microfinance-bank-ng",
            "ussd_code": "",
            "bank_logo": "",
        },
        {
            "bank_code": "090179",
            "cbn_code": "",
            "name": "Fast MFB",
            "bank_short_name": "",
            "ussd_code": "",
            "logo": "",
        },
        {
            "bank_code": "090318",
            "cbn_code": "",
            "name": "Federal University Dutse MFB",
            "bank_short_name": "",
            "ussd_code": "",
            "logo": "",
        },
        {
            "bank_code": "090298",
            "cbn_code": "",
            "name": "Fedpoly Nasarawa MFB",
            "bank_short_name": "",
            "ussd_code": "",
            "logo": "",
        },
        {
            "bank_code": "000007",
            "cbn_code": "070",
            "name": "Fidelity Bank",
            "bank_short_name": "fidelity",
            "ussd_code": "*770#",
            "logo": "https://nigeria-banks.onrender.com/static/images/fidelity.png",
        },
        {
            "bank_code": "100019",
            "cbn_code": "",
            "name": "Fidelity Mobile",
            "bank_short_name": "",
            "ussd_code": "",
            "logo": "",
        },
        {
            "bank_code": "090126",
            "cbn_code": "",
            "name": "Fidfund MFB",
            "bank_short_name": "",
            "ussd_code": "",
            "logo": "",
        },
        {
            "bank_code": "090111",
            "cbn_code": "",
            "name": "Finatrust MFB",
            "bank_short_name": "",
            "ussd_code": "",
            "logo": "",
        },
        {
            "bank_code": "",
            "cbn_code": "51314",
            "name": "Firmus MFB",
            "bank_short_name": "firmus-mfb",
            "ussd_code": "",
            "bank_logo": "",
        },
        {
            "bank_code": "110004",
            "cbn_code": "",
            "name": "First Apple",
            "bank_short_name": "",
            "ussd_code": "",
            "logo": "",
        },
        {
            "bank_code": "000016",
            "cbn_code": "214",
            "name": "First Bank of Nigeria",
            "bank_short_name": "firstbank",
            "ussd_code": "*894#",
            "logo": "https://nigeria-banks.onrender.com/static/images/firstbank.png",
        },
        {
            "bank_code": "000003",
            "cbn_code": "214",
            "name": "First City Monument Bank",
            "bank_short_name": "fcmb",
            "ussd_code": "*329#",
            "logo": "https://nigeria-banks.onrender.com/static/images/fcmb.png",
        },
        {
            "bank_code": "070014",
            "cbn_code": "",
            "name": "First Gen Mortgage Bank",
            "bank_short_name": "",
            "ussd_code": "",
            "logo": "",
        },
        {
            "bank_code": "090163",
            "cbn_code": "",
            "name": "First Multiple MFB",
            "bank_short_name": "",
            "ussd_code": "",
            "logo": "",
        },
        {
            "bank_code": "090285",
            "cbn_code": "",
            "name": "First Option MFB",
            "bank_short_name": "",
            "ussd_code": "",
            "logo": "",
        },
        {
            "bank_code": "090164",
            "cbn_code": "",
            "name": "First Royal MFB",
            "bank_short_name": "",
            "ussd_code": "",
            "logo": "",
        },
        {
            "bank_code": "090005",
            "cbn_code": "",
            "name": "First Trust Mortgage Bank",
            "bank_short_name": "",
            "ussd_code": "",
            "logo": "",
        },
        {
            "bank_code": "090107",
            "cbn_code": "",
            "name": "First Trust Mortgage Bank",
            "bank_short_name": "",
            "ussd_code": "",
            "logo": "",
        },
        {
            "bank_code": "",
            "cbn_code": "107",
            "name": "FirstTrust Mortgage Bank Nigeria",
            "bank_short_name": "firsttrust-mortgage-bank-nigeria-ng",
            "ussd_code": "",
            "bank_logo": "",
        },
        {
            "bank_code": "100014",
            "cbn_code": "",
            "name": "Firstmonie Wallet",
            "bank_short_name": "",
            "ussd_code": "",
            "logo": "",
        },
        {
            "bank_code": "110002",
            "cbn_code": "",
            "name": "Flutterwave Tech Solutions",
            "bank_short_name": "",
            "ussd_code": "",
            "logo": "",
        },
        {
            "bank_code": "070002",
            "cbn_code": "",
            "name": "Fortis MFB",
            "bank_short_name": "",
            "ussd_code": "",
            "logo": "",
        },
        {
            "bank_code": "100016",
            "cbn_code": "",
            "name": "Fortis Mobile",
            "bank_short_name": "",
            "ussd_code": "",
            "logo": "",
        },
        {
            "bank_code": "090145",
            "cbn_code": "",
            "name": "Full Range MFB",
            "bank_short_name": "",
            "ussd_code": "",
            "logo": "",
        },
        {
            "bank_code": "090158",
            "cbn_code": "",
            "name": "Futo MFB",
            "bank_short_name": "",
            "ussd_code": "",
            "logo": "",
        },
        {
            "bank_code": "100009",
            "cbn_code": "315",
            "name": "GT Mobile Money",
            "bank_short_name": "gtb-mobile",
            "ussd_code": "",
            "logo": "",
        },
        {
            "bank_code": "090168",
            "cbn_code": "",
            "name": "Gashua MFB",
            "bank_short_name": "",
            "ussd_code": "",
            "logo": "",
        },
        {
            "bank_code": "070009",
            "cbn_code": "812",
            "name": "Gateway Mortgage Bank",
            "bank_short_name": "",
            "ussd_code": "",
            "logo": "",
        },
        {
            "bank_code": "000027",
            "cbn_code": "00103",
            "name": "Globus Bank",
            "bank_short_name": "",
            "ussd_code": "",
            "logo": "",
        },
        {
            "bank_code": "090278",
            "cbn_code": "",
            "name": "Glory MFB",
            "bank_short_name": "",
            "ussd_code": "",
            "logo": "",
        },
        {
            "bank_code": "",
            "cbn_code": "100022",
            "name": "GoMoney",
            "bank_short_name": "gomoney",
            "ussd_code": "",
            "bank_logo": "",
        },
        {
            "bank_code": "100022",
            "cbn_code": "None",
            "name": "Gomoney",
            "bank_short_name": "sterling",
            "ussd_code": "",
            "logo": "",
        },
        {
            "bank_code": "",
            "cbn_code": "50739",
            "name": "Goodnews Microfinance Bank",
            "bank_short_name": "goodnews-microfinance-bank-ng",
            "ussd_code": "",
            "bank_logo": "",
        },
        {
            "bank_code": "090122",
            "cbn_code": "",
            "name": "Gowans MFB",
            "bank_short_name": "",
            "ussd_code": "",
            "logo": "",
        },
        {
            "bank_code": "090178",
            "cbn_code": "",
            "name": "Greenbank MFB",
            "bank_short_name": "",
            "ussd_code": "",
            "logo": "",
        },
        {
            "bank_code": "090269",
            "cbn_code": "",
            "name": "Greenville MFB",
            "bank_short_name": "",
            "ussd_code": "",
            "logo": "",
        },
        {
            "bank_code": "",
            "cbn_code": "562",
            "name": "Greenwich Merchant Bank",
            "bank_short_name": "greenwich-merchant-bank-ng",
            "ussd_code": "",
            "bank_logo": "",
        },
        {
            "bank_code": "090195",
            "cbn_code": "",
            "name": "Grooming MFB",
            "bank_short_name": "",
            "ussd_code": "",
            "logo": "",
        },
        {
            "bank_code": "000013",
            "cbn_code": "058",
            "name": "Guaranty Trust Bank",
            "bank_short_name": "gtb",
            "ussd_code": "*737#",
            "logo": "https://nigeria-banks.onrender.com/static/images/gtb.png",
        },
        {
            "bank_code": "090147",
            "cbn_code": "51251",
            "name": "Hackman MFB",
            "bank_short_name": "",
            "ussd_code": "",
            "logo": "",
        },
        {
            "bank_code": "070017",
            "cbn_code": "",
            "name": "Haggai Mortgage Bank",
            "bank_short_name": "",
            "ussd_code": "",
            "logo": "",
        },
        {
            "bank_code": "090291",
            "cbn_code": "",
            "name": "Hala MFB",
            "bank_short_name": "",
            "ussd_code": "",
            "logo": "",
        },
        {
            "bank_code": "090121",
            "cbn_code": "50383",
            "name": "Hasal MFB",
            "bank_short_name": "mfb",
            "ussd_code": "*322*127#",
            "logo": "https://nigeria-banks.onrender.com/static/images/mfb.png",
        },
        {
            "bank_code": "100017",
            "cbn_code": "",
            "name": "Hedonmark",
            "bank_short_name": "",
            "ussd_code": "",
            "logo": "",
        },
        {
            "bank_code": "000020",
            "cbn_code": "030",
            "name": "Heritage Bank",
            "bank_short_name": "heritage",
            "ussd_code": "*322#",
            "logo": "https://nigeria-banks.onrender.com/static/images/heritage.png",
        },
        {
            "bank_code": "",
            "cbn_code": "120002",
            "name": "HopePSB",
            "bank_short_name": "hopepsb-ng",
            "ussd_code": "",
            "bank_logo": "",
        },
        {
            "bank_code": "090149",
            "cbn_code": "",
            "name": "IRL MFB",
            "bank_short_name": "",
            "ussd_code": "",
            "logo": "",
        },
        {
            "bank_code": "090118",
            "cbn_code": "51244",
            "name": "Ibile MFB",
            "bank_short_name": "",
            "ussd_code": "",
            "logo": "",
        },
        {
            "bank_code": "090275",
            "cbn_code": "",
            "name": "Ikire MFB",
            "bank_short_name": "",
            "ussd_code": "",
            "logo": "",
        },
        {
            "bank_code": "090279",
            "cbn_code": "",
            "name": "Ikire MFB",
            "bank_short_name": "",
            "ussd_code": "",
            "logo": "",
        },
        {
            "bank_code": "",
            "cbn_code": "50439",
            "name": "Ikoyi Osun MFB",
            "bank_short_name": "ikoyi-osun-mfb",
            "ussd_code": "",
            "bank_logo": "",
        },
        {
            "bank_code": "",
            "cbn_code": "50442",
            "name": "Ilaro Poly Microfinance Bank",
            "bank_short_name": "ilaro-poly-microfinance-bank-ng",
            "ussd_code": "",
            "bank_logo": "",
        },
        {
            "bank_code": "090258",
            "cbn_code": "",
            "name": "Imo State MFB",
            "bank_short_name": "",
            "ussd_code": "",
            "logo": "",
        },
        {
            "bank_code": "100024",
            "cbn_code": "",
            "name": "Imperial Homes Mortgage Bank",
            "bank_short_name": "",
            "ussd_code": "",
            "logo": "",
        },
        {
            "bank_code": "090157",
            "cbn_code": "50457",
            "name": "Infinity MFB",
            "bank_short_name": "",
            "ussd_code": "",
            "logo": "",
        },
        {
            "bank_code": "070016",
            "cbn_code": "",
            "name": "Infinity Trust Mortgage Bank",
            "bank_short_name": "",
            "ussd_code": "",
            "logo": "",
        },
        {
            "bank_code": "100029",
            "cbn_code": "",
            "name": "Innovectives Kesh",
            "bank_short_name": "",
            "ussd_code": "",
            "logo": "",
        },
        {
            "bank_code": "110003",
            "cbn_code": "",
            "name": "Interswitch",
            "bank_short_name": "",
            "ussd_code": "",
            "logo": "",
        },
        {
            "bank_code": "090211",
            "cbn_code": "",
            "name": "Itex Integrated Services",
            "bank_short_name": "",
            "ussd_code": "",
            "logo": "",
        },
        {
            "bank_code": "000006",
            "cbn_code": "301",
            "name": "Jaiz Bank",
            "bank_short_name": "jaiz",
            "ussd_code": "*389*301#",
            "logo": "https://nigeria-banks.onrender.com/static/images/jaiz.png",
        },
        {
            "bank_code": "090003",
            "cbn_code": "",
            "name": "Jubilee Life",
            "bank_short_name": "",
            "ussd_code": "",
            "logo": "",
        },
        {
            "bank_code": "090191",
            "cbn_code": "",
            "name": "KCMB MFB",
            "bank_short_name": "",
            "ussd_code": "",
            "logo": "",
        },
        {
            "bank_code": "090320",
            "cbn_code": "50502",
            "name": "Kadpoly MFB",
            "bank_short_name": "",
            "ussd_code": "",
            "logo": "",
        },
        {
            "bank_code": "100015",
            "cbn_code": "",
            "name": "Kegow",
            "bank_short_name": "",
            "ussd_code": "",
            "logo": "",
        },
        {
            "bank_code": "000002",
            "cbn_code": "082",
            "name": "Keystone Bank",
            "bank_short_name": "keystone",
            "ussd_code": "*7111#",
            "logo": "https://nigeria-banks.onrender.com/static/images/keystone.png",
        },
        {
            "bank_code": "090299",
            "cbn_code": "",
            "name": "Kontagora MFB",
            "bank_short_name": "",
            "ussd_code": "",
            "logo": "",
        },
        {
            "bank_code": "090380",
            "cbn_code": "50200",
            "name": "Kredi Bank",
            "bank_short_name": "",
            "ussd_code": "",
            "logo": "",
        },
        {
            "bank_code": "090267",
            "cbn_code": "50211",
            "name": "Kuda MFB",
            "bank_short_name": "kuda",
            "ussd_code": "",
            "logo": "https://nigeria-banks.onrender.com/static/images/kuda.png",
        },
        {
            "bank_code": "090177",
            "cbn_code": "",
            "name": "LAPO MFB",
            "bank_short_name": "",
            "ussd_code": "",
            "logo": "",
        },
        {
            "bank_code": "090155",
            "cbn_code": "",
            "name": "La Fayette MFB",
            "bank_short_name": "",
            "ussd_code": "",
            "logo": "",
        },
        {
            "bank_code": "070012",
            "cbn_code": "90052",
            "name": "Lagos Building Investment Company",
            "bank_short_name": "",
            "ussd_code": "",
            "logo": "",
        },
        {
            "bank_code": "090271",
            "cbn_code": "",
            "name": "Lavender MFB",
            "bank_short_name": "",
            "ussd_code": "",
            "logo": "",
        },
        {
            "bank_code": "",
            "cbn_code": "50549",
            "name": "Links MFB",
            "bank_short_name": "links-mfb",
            "ussd_code": "",
            "bank_logo": "",
        },
        {
            "bank_code": "",
            "cbn_code": "031",
            "name": "Living Trust Mortgage Bank",
            "bank_short_name": "living-trust-mortgage-bank",
            "ussd_code": "",
            "bank_logo": "",
        },
        {
            "bank_code": "",
            "cbn_code": "303",
            "name": "Lotus Bank",
            "bank_short_name": "lotus-bank",
            "ussd_code": "",
            "bank_logo": "",
        },
        {
            "bank_code": "090265",
            "cbn_code": "",
            "name": "Lovonus MFB",
            "bank_short_name": "",
            "ussd_code": "",
            "logo": "",
        },
        {
            "bank_code": "100011",
            "cbn_code": "",
            "name": "M-Kudi",
            "bank_short_name": "",
            "ussd_code": "",
            "logo": "",
        },
        {
            "bank_code": "",
            "cbn_code": "120003",
            "name": "MTN Momo PSB",
            "bank_short_name": "mtn-momo-psb-ng",
            "ussd_code": "",
            "bank_logo": "",
        },
        {
            "bank_code": "090171",
            "cbn_code": "",
            "name": "Mainstreet MFB",
            "bank_short_name": "",
            "ussd_code": "",
            "logo": "",
        },
        {
            "bank_code": "090174",
            "cbn_code": "",
            "name": "Malachy MFB",
            "bank_short_name": "",
            "ussd_code": "",
            "logo": "",
        },
        {
            "bank_code": "",
            "cbn_code": "50563",
            "name": "Mayfair MFB",
            "bank_short_name": "mayfair-mfb",
            "ussd_code": "",
            "bank_logo": "",
        },
        {
            "bank_code": "090280",
            "cbn_code": "",
            "name": "Megapraise MFB",
            "bank_short_name": "",
            "ussd_code": "",
            "logo": "",
        },
        {
            "bank_code": "090113",
            "cbn_code": "",
            "name": "Microvis MFB",
            "bank_short_name": "",
            "ussd_code": "",
            "logo": "",
        },
        {
            "bank_code": "090192",
            "cbn_code": "",
            "name": "Midland MFB",
            "bank_short_name": "",
            "ussd_code": "",
            "logo": "",
        },
        {
            "bank_code": "100027",
            "cbn_code": "",
            "name": "Mimoney Intellifin Solutions",
            "bank_short_name": "",
            "ussd_code": "",
            "logo": "",
        },
        {
            "bank_code": "",
            "cbn_code": "50304",
            "name": "Mint MFB",
            "bank_short_name": "mint-mfb",
            "ussd_code": "",
            "bank_logo": "",
        },
        {
            "bank_code": "090281",
            "cbn_code": "",
            "name": "Mint-Finex MFB",
            "bank_short_name": "",
            "ussd_code": "",
            "logo": "",
        },
        {
            "bank_code": "090129",
            "cbn_code": "51269",
            "name": "Money Trust MFB",
            "bank_short_name": "",
            "ussd_code": "",
            "logo": "",
        },
        {
            "bank_code": "100020",
            "cbn_code": "",
            "name": "Moneybox",
            "bank_short_name": "",
            "ussd_code": "",
            "logo": "",
        },
        {
            "bank_code": "090190",
            "cbn_code": "",
            "name": "Mutual Benefits Mifb",
            "bank_short_name": "",
            "ussd_code": "",
            "logo": "",
        },
        {
            "bank_code": "090151",
            "cbn_code": "",
            "name": "Mutual Trust MFB",
            "bank_short_name": "",
            "ussd_code": "",
            "logo": "",
        },
        {
            "bank_code": "010101",
            "cbn_code": "",
            "name": "N/A",
            "bank_short_name": "n/a",
            "ussd_code": "",
            "logo": "",
        },
        {
            "bank_code": "090152",
            "cbn_code": "",
            "name": "Nargata MFB",
            "bank_short_name": "",
            "ussd_code": "",
            "logo": "",
        },
        {
            "bank_code": "090128",
            "cbn_code": "",
            "name": "Ndiorah MFB",
            "bank_short_name": "",
            "ussd_code": "",
            "logo": "",
        },
        {
            "bank_code": "090205",
            "cbn_code": "",
            "name": "New Dawn MFB",
            "bank_short_name": "",
            "ussd_code": "",
            "logo": "",
        },
        {
            "bank_code": "090108",
            "cbn_code": "",
            "name": "New Prudential Bank",
            "bank_short_name": "",
            "ussd_code": "",
            "logo": "",
        },
        {
            "bank_code": "090263",
            "cbn_code": "",
            "name": "Nigerian Navy MFB",
            "bank_short_name": "",
            "ussd_code": "",
            "logo": "",
        },
        {
            "bank_code": "070001",
            "cbn_code": "",
            "name": "Nigerian Police Force MFB",
            "bank_short_name": "",
            "ussd_code": "",
            "logo": "",
        },
        {
            "bank_code": "090194",
            "cbn_code": "",
            "name": "Nirsal MFB",
            "bank_short_name": "",
            "ussd_code": "",
            "logo": "",
        },
        {
            "bank_code": "090283",
            "cbn_code": "",
            "name": "Nnew Women MFB",
            "bank_short_name": "",
            "ussd_code": "",
            "logo": "",
        },
        {
            "bank_code": "060003",
            "cbn_code": "561",
            "name": "Nova Merchant Bank",
            "bank_short_name": "",
            "ussd_code": "",
            "logo": "",
        },
        {
            "bank_code": "090119",
            "cbn_code": "",
            "name": "Ohafia MFB",
            "bank_short_name": "",
            "ussd_code": "",
            "logo": "",
        },
        {
            "bank_code": "090161",
            "cbn_code": "",
            "name": "Okpoga MFB",
            "bank_short_name": "",
            "ussd_code": "",
            "logo": "",
        },
        {
            "bank_code": "090272",
            "cbn_code": "",
            "name": "Olabisi Onabanjo University MFB",
            "bank_short_name": "",
            "ussd_code": "",
            "logo": "",
        },
        {
            "bank_code": "090295",
            "cbn_code": "",
            "name": "Omiye MFB",
            "bank_short_name": "",
            "ussd_code": "",
            "logo": "",
        },
        {
            "bank_code": "070007",
            "cbn_code": "",
            "name": "Omoluabi Mortgage Bank",
            "bank_short_name": "",
            "ussd_code": "",
            "logo": "",
        },
        {
            "bank_code": "100026",
            "cbn_code": "565",
            "name": "One Finance",
            "bank_short_name": "one-finace",
            "ussd_code": "*1303#",
            "logo": "https://nigeria-banks.onrender.com/static/images/one-finace.png",
        },
        {
            "bank_code": "100002",
            "cbn_code": "100002",
            "name": "Paga",
            "bank_short_name": "",
            "ussd_code": "",
            "logo": "",
        },
        {
            "bank_code": "070008",
            "cbn_code": "",
            "name": "Page Financials",
            "bank_short_name": "",
            "ussd_code": "",
            "logo": "",
        },
        {
            "bank_code": "",
            "cbn_code": "999991",
            "name": "PalmPay",
            "bank_short_name": "palmpay",
            "ussd_code": "",
            "bank_logo": "",
        },
        {
            "bank_code": "100033",
            "cbn_code": "",
            "name": "Palmpay",
            "bank_short_name": "",
            "ussd_code": "",
            "logo": "",
        },
        {
            "bank_code": "090004",
            "cbn_code": "104",
            "name": "Parallex MFB",
            "bank_short_name": "parallex",
            "ussd_code": "*322*318*0#",
            "logo": "https://nigeria-banks.onrender.com/static/images/parallex.png",
        },
        {
            "bank_code": "100003",
            "cbn_code": "311",
            "name": "Parkway-Readycash",
            "bank_short_name": "parkway",
            "ussd_code": "",
            "logo": "",
        },
        {
            "bank_code": "090317",
            "cbn_code": "",
            "name": "Patrickgold MFB",
            "bank_short_name": "",
            "ussd_code": "",
            "logo": "",
        },
        {
            "bank_code": "110001",
            "cbn_code": "",
            "name": "Payattitude Online",
            "bank_short_name": "",
            "ussd_code": "",
            "logo": "",
        },
        {
            "bank_code": "100004",
            "cbn_code": "999992",
            "name": "Paycom (Opay)",
            "bank_short_name": "paycom",
            "ussd_code": "",
            "logo": "",
        },
        {
            "bank_code": "110006",
            "cbn_code": "",
            "name": "Paystack Payments",
            "bank_short_name": "",
            "ussd_code": "",
            "logo": "",
        },
        {
            "bank_code": "",
            "cbn_code": "50743",
            "name": "Peace Microfinance Bank",
            "bank_short_name": "peace-microfinance-bank-ng",
            "ussd_code": "",
            "bank_logo": "",
        },
        {
            "bank_code": "090137",
            "cbn_code": "",
            "name": "Pecantrust MFB",
            "bank_short_name": "",
            "ussd_code": "",
            "logo": "",
        },
        {
            "bank_code": "090196",
            "cbn_code": "",
            "name": "Pennywise MFB",
            "bank_short_name": "",
            "ussd_code": "",
            "logo": "",
        },
        {
            "bank_code": "090135",
            "cbn_code": "51146",
            "name": "Personal Trust MFB",
            "bank_short_name": "",
            "ussd_code": "",
            "logo": "",
        },
        {
            "bank_code": "090165",
            "cbn_code": "50746",
            "name": "Petra MFB",
            "bank_short_name": "",
            "ussd_code": "",
            "logo": "",
        },
        {
            "bank_code": "090289",
            "cbn_code": "",
            "name": "Pillar MFB",
            "bank_short_name": "",
            "ussd_code": "",
            "logo": "",
        },
        {
            "bank_code": "070013",
            "cbn_code": "",
            "name": "Platinum Mortgage Bank",
            "bank_short_name": "",
            "ussd_code": "",
            "logo": "",
        },
        {
            "bank_code": "000008",
            "cbn_code": "076",
            "name": "Polaris Bank",
            "bank_short_name": "PBL",
            "ussd_code": "*833#",
            "logo": "https://nigeria-banks.onrender.com/static/images/PBL.png",
        },
        {
            "bank_code": "",
            "cbn_code": "50864",
            "name": "Polyunwana MFB",
            "bank_short_name": "polyunwana-mfb-ng",
            "ussd_code": "",
            "bank_logo": "",
        },
        {
            "bank_code": "090296",
            "cbn_code": "",
            "name": "Polyuwana MFB",
            "bank_short_name": "",
            "ussd_code": "",
            "logo": "",
        },
        {
            "bank_code": "",
            "cbn_code": "105",
            "name": "PremiumTrust Bank",
            "bank_short_name": "premiumtrust-bank-ng",
            "ussd_code": "",
            "bank_logo": "",
        },
        {
            "bank_code": "090274",
            "cbn_code": "",
            "name": "Prestige MFB",
            "bank_short_name": "",
            "ussd_code": "",
            "logo": "",
        },
        {
            "bank_code": "000023",
            "cbn_code": "101",
            "name": "Providus Bank",
            "bank_short_name": "providus",
            "ussd_code": "",
            "logo": "https://nigeria-banks.onrender.com/static/images/providus.png",
        },
        {
            "bank_code": "090303",
            "cbn_code": "",
            "name": "Purplemoney MFB",
            "bank_short_name": "",
            "ussd_code": "",
            "logo": "",
        },
        {
            "bank_code": "",
            "cbn_code": "51293",
            "name": "QuickFund MFB",
            "bank_short_name": "quickfund-mfb",
            "ussd_code": "",
            "bank_logo": "",
        },
        {
            "bank_code": "090261",
            "cbn_code": "",
            "name": "Quickfund MFB",
            "bank_short_name": "",
            "ussd_code": "",
            "logo": "",
        },
        {
            "bank_code": "",
            "cbn_code": "50767",
            "name": "ROCKSHIELD MICROFINANCE BANK",
            "bank_short_name": "rockshield-microfinance-bank-ng",
            "ussd_code": "",
            "bank_logo": "",
        },
        {
            "bank_code": "090170",
            "cbn_code": "",
            "name": "Rahama MFB",
            "bank_short_name": "",
            "ussd_code": "",
            "logo": "",
        },
        {
            "bank_code": "000024",
            "cbn_code": "502",
            "name": "Rand Merchant Bank",
            "bank_short_name": "",
            "ussd_code": "",
            "logo": "",
        },
        {
            "bank_code": "070011",
            "cbn_code": "90067",
            "name": "Refuge Mortgage Bank",
            "bank_short_name": "",
            "ussd_code": "",
            "logo": "",
        },
        {
            "bank_code": "090125",
            "cbn_code": "",
            "name": "Regent MFB",
            "bank_short_name": "",
            "ussd_code": "",
            "logo": "",
        },
        {
            "bank_code": "090173",
            "cbn_code": "",
            "name": "Reliance MFB",
            "bank_short_name": "",
            "ussd_code": "",
            "logo": "",
        },
        {
            "bank_code": "090198",
            "cbn_code": "",
            "name": "Renmoney MFB",
            "bank_short_name": "",
            "ussd_code": "",
            "logo": "",
        },
        {
            "bank_code": "090132",
            "cbn_code": "",
            "name": "Richway MFB",
            "bank_short_name": "",
            "ussd_code": "",
            "logo": "",
        },
        {
            "bank_code": "090405",
            "cbn_code": "50515",
            "name": "Rolez Bank",
            "bank_short_name": "None",
            "ussd_code": "",
            "logo": "",
        },
        {
            "bank_code": "090138",
            "cbn_code": "",
            "name": "Royal Exchange MFB",
            "bank_short_name": "",
            "ussd_code": "",
            "logo": "",
        },
        {
            "bank_code": "090175",
            "cbn_code": "125",
            "name": "Rubies MFB",
            "bank_short_name": "RMB",
            "ussd_code": "*7797#",
            "logo": "https://nigeria-banks.onrender.com/static/images/RMB.png",
        },
        {
            "bank_code": "090286",
            "cbn_code": "951113",
            "name": "Safe Haven MFB",
            "bank_short_name": "",
            "ussd_code": "",
            "logo": "",
        },
        {
            "bank_code": "090006",
            "cbn_code": "",
            "name": "Safetrust Mortgage Bank",
            "bank_short_name": "",
            "ussd_code": "",
            "logo": "",
        },
        {
            "bank_code": "090140",
            "cbn_code": "",
            "name": "Sagamu MFB",
            "bank_short_name": "",
            "ussd_code": "",
            "logo": "",
        },
        {
            "bank_code": "090112",
            "cbn_code": "",
            "name": "Seed Capital MFB",
            "bank_short_name": "",
            "ussd_code": "",
            "logo": "",
        },
        {
            "bank_code": "",
            "cbn_code": "50582",
            "name": "Shield MFB",
            "bank_short_name": "shield-mfb-ng",
            "ussd_code": "",
            "bank_logo": "",
        },
        {
            "bank_code": "",
            "cbn_code": "50800",
            "name": "Solid Rock MFB",
            "bank_short_name": "solid-rock-mfb",
            "ussd_code": "",
            "bank_logo": "",
        },
        {
            "bank_code": "090325",
            "cbn_code": "51310",
            "name": "Sparkle Bank",
            "bank_short_name": "SPKL",
            "ussd_code": "",
            "logo": "https://nigeria-banks.onrender.com/static/images/SPKL.png",
        },
        {
            "bank_code": "000012",
            "cbn_code": "221",
            "name": "Stanbic IBTC",
            "bank_short_name": "stanbic",
            "ussd_code": "*909#",
            "logo": "https://nigeria-banks.onrender.com/static/images/stanbic.png",
        },
        {
            "bank_code": "100007",
            "cbn_code": "304",
            "name": "Stanbic IBTC @Ease Wal",
            "bank_short_name": "stanbic-mobile",
            "ussd_code": "",
            "logo": "",
        },
        {
            "bank_code": "000021",
            "cbn_code": "068",
            "name": "Standard Chartered Bank",
            "bank_short_name": "standard-chartered",
            "ussd_code": "",
            "logo": "https://nigeria-banks.onrender.com/static/images/standard-chartered.png",
        },
        {
            "bank_code": "090162",
            "cbn_code": "",
            "name": "Stanford MFB",
            "bank_short_name": "",
            "ussd_code": "",
            "logo": "",
        },
        {
            "bank_code": "090262",
            "cbn_code": "51253",
            "name": "Stellas MFB",
            "bank_short_name": "",
            "ussd_code": "",
            "logo": "",
        },
        {
            "bank_code": "000001",
            "cbn_code": "232",
            "name": "Sterling Bank",
            "bank_short_name": "sterling",
            "ussd_code": "*822#",
            "logo": "https://nigeria-banks.onrender.com/static/images/sterling.png",
        },
        {
            "bank_code": "090305",
            "cbn_code": "",
            "name": "Sulspap MFB",
            "bank_short_name": "",
            "ussd_code": "",
            "logo": "",
        },
        {
            "bank_code": "000022",
            "cbn_code": "100",
            "name": "Suntrust Bank",
            "bank_short_name": "suntrust",
            "ussd_code": "*5230#",
            "logo": "https://nigeria-banks.onrender.com/static/images/suntrust.png",
        },
        {
            "bank_code": "",
            "cbn_code": "50968",
            "name": "Supreme MFB",
            "bank_short_name": "supreme-mfb-ng",
            "ussd_code": "",
            "bank_logo": "",
        },
        {
            "bank_code": "090115",
            "cbn_code": "51211",
            "name": "TCF MFB",
            "bank_short_name": "tcf-bank",
            "ussd_code": "*908#",
            "logo": "https://nigeria-banks.onrender.com/static/images/tcf-bank.png",
        },
        {
            "bank_code": "100023",
            "cbn_code": "",
            "name": "Tagpay",
            "bank_short_name": "",
            "ussd_code": "",
            "logo": "",
        },
        {
            "bank_code": "000026",
            "cbn_code": "302",
            "name": "Taj Bank",
            "bank_short_name": "taj-bank",
            "ussd_code": "*898#",
            "logo": "https://nigeria-banks.onrender.com/static/images/taj-bank.png",
        },
        {
            "bank_code": "",
            "cbn_code": "090560",
            "name": "Tanadi Microfinance Bank",
            "bank_short_name": "tanadi-microfinance-bank-ng",
            "ussd_code": "",
            "bank_logo": "",
        },
        {
            "bank_code": "110007",
            "cbn_code": "",
            "name": "TeamApt",
            "bank_short_name": "",
            "ussd_code": "",
            "logo": "",
        },
        {
            "bank_code": "100010",
            "cbn_code": "",
            "name": "Teasy Mobile",
            "bank_short_name": "",
            "ussd_code": "",
            "logo": "",
        },
        {
            "bank_code": "000025",
            "cbn_code": "100039",
            "name": "Titan Trust Bank",
            "bank_short_name": "titan-trust",
            "ussd_code": "*922#",
            "logo": "https://nigeria-banks.onrender.com/static/images/titan-trust.png",
        },
        {
            "bank_code": "090146",
            "cbn_code": "",
            "name": "Trident MFB",
            "bank_short_name": "",
            "ussd_code": "",
            "logo": "",
        },
        {
            "bank_code": "090123",
            "cbn_code": "",
            "name": "Trustbanc J6 MFB",
            "bank_short_name": "",
            "ussd_code": "",
            "logo": "",
        },
        {
            "bank_code": "090276",
            "cbn_code": "",
            "name": "Trustfund MFB",
            "bank_short_name": "",
            "ussd_code": "",
            "logo": "",
        },
        {
            "bank_code": "",
            "cbn_code": "50840",
            "name": "U&C Microfinance Bank Ltd (U AND C MFB)",
            "bank_short_name": "uc-microfinance-bank-ltd-u-and-c-mfb-ng",
            "ussd_code": "",
            "bank_logo": "",
        },
        {
            "bank_code": "090266",
            "cbn_code": "",
            "name": "UNIBEN MFB",
            "bank_short_name": "",
            "ussd_code": "",
            "logo": "",
        },
        {
            "bank_code": "090193",
            "cbn_code": "50871",
            "name": "UNICAL MFB",
            "bank_short_name": "",
            "ussd_code": "",
            "logo": "",
        },
        {
            "bank_code": "",
            "cbn_code": "MFB51322",
            "name": "Uhuru MFB",
            "bank_short_name": "uhuru-mfb-ng",
            "ussd_code": "",
            "bank_logo": "",
        },
        {
            "bank_code": "",
            "cbn_code": "50870",
            "name": "Unaab Microfinance Bank Limited",
            "bank_short_name": "unaab-microfinance-bank-limited-ng",
            "ussd_code": "",
            "bank_logo": "",
        },
        {
            "bank_code": "",
            "cbn_code": "51316",
            "name": "Unilag Microfinance Bank",
            "bank_short_name": "unilag-microfinance-bank-ng",
            "ussd_code": "",
            "bank_logo": "",
        },
        {
            "bank_code": "000018",
            "cbn_code": "032",
            "name": "Union Bank of Nigeria",
            "bank_short_name": "unionbank",
            "ussd_code": "*826#",
            "logo": "https://nigeria-banks.onrender.com/static/images/unionbank.png",
        },
        {
            "bank_code": "000004",
            "cbn_code": "033",
            "name": "United Bank for Africa",
            "bank_short_name": "uba",
            "ussd_code": "*919#",
            "logo": "https://nigeria-banks.onrender.com/static/images/uba.png",
        },
        {
            "bank_code": "000011",
            "cbn_code": "215",
            "name": "Unity Bank",
            "bank_short_name": "unity-bank",
            "ussd_code": "*7799#",
            "logo": "https://nigeria-banks.onrender.com/static/images/unity-bank.png",
        },
        {
            "bank_code": "090251",
            "cbn_code": "",
            "name": "Unn MFB",
            "bank_short_name": "",
            "ussd_code": "",
            "logo": "",
        },
        {
            "bank_code": "090110",
            "cbn_code": "566",
            "name": "VFD MFB",
            "bank_short_name": "vfd",
            "ussd_code": "",
            "logo": "https://nigeria-banks.onrender.com/static/images/vfd.png",
        },
        {
            "bank_code": "090150",
            "cbn_code": "",
            "name": "Virtue MFB",
            "bank_short_name": "",
            "ussd_code": "",
            "logo": "",
        },
        {
            "bank_code": "090139",
            "cbn_code": "",
            "name": "Visa MFB",
            "bank_short_name": "",
            "ussd_code": "",
            "logo": "",
        },
        {
            "bank_code": "100012",
            "cbn_code": "",
            "name": "Vtnetwork",
            "bank_short_name": "",
            "ussd_code": "",
            "logo": "",
        },
        {
            "bank_code": "000017",
            "cbn_code": "035",
            "name": "Wema Bank",
            "bank_short_name": "wema",
            "ussd_code": "*945#",
            "logo": "https://nigeria-banks.onrender.com/static/images/wema.png",
        },
        {
            "bank_code": "090120",
            "cbn_code": "",
            "name": "Wetland MFB",
            "bank_short_name": "",
            "ussd_code": "",
            "logo": "",
        },
        {
            "bank_code": "090124",
            "cbn_code": "",
            "name": "Xslnce MFB",
            "bank_short_name": "",
            "ussd_code": "",
            "logo": "",
        },
        {
            "bank_code": "090142",
            "cbn_code": "",
            "name": "Yes MFB",
            "bank_short_name": "",
            "ussd_code": "",
            "logo": "",
        },
        {
            "bank_code": "000015",
            "cbn_code": "057",
            "name": "Zenith Bank",
            "bank_short_name": "zenith",
            "ussd_code": "*966#",
            "logo": "https://nigeria-banks.onrender.com/static/images/zenith.png",
        },
        {
            "bank_code": "100018",
            "cbn_code": "322",
            "name": "Zenith Mobile",
            "bank_short_name": "zenith-mobile",
            "ussd_code": "",
            "logo": "",
        },
        {
            "bank_code": "100025",
            "cbn_code": "",
            "name": "Zinternet",
            "bank_short_name": "",
            "ussd_code": "",
            "logo": "",
        },
    ]

    return data


"""
ALL DETAILS NOT AVAILABLE FOR THIS BANKS:

{
    "bank_code": "110005",
    "cbn_code": "",
    "name": "3Line",
    "bank_short_name": "3Line",
    "ussd_code": "",
    "logo": "https://nigeria-banks.onrender.com/static/images/3Line.png",
},
{
    "bank_code": "",
    "cbn_code": "120001",
    "name": "9mobile 9Payment Service Bank",
    "bank_short_name": "9psb",
    "ussd_code": "*990#",
    "bank_logo": "https://nigeria-banks.onrender.com/static/images/9psb.png",
},

{
    "bank_code": "",
    "cbn_code": "51341",
    "name": "AMPERSAND MICROFINANCE BANK",
    "bank_short_name": "ampersand-microfinance-bank-ng",
    "ussd_code": "",
    "bank_logo": "",
},

{
    "bank_code": "",
    "cbn_code": "51312",
    "name": "Abulesoro MFB",
    "bank_short_name": "abulesoro-mfb-ng",
    "ussd_code": "",
    "bank_logo": "",
},

{
    "bank_code": "090292",
    "cbn_code": "",
    "name": "Afekhafe MFB",
    "bank_short_name": "",
    "ussd_code": "",
    "logo": "",
},

{
    "bank_code": "",
    "cbn_code": "50036",
    "name": "Ahmadu Bello University Microfinance Bank",
    "bank_short_name": "ahmadu-bello-university-microfinance-bank-ng",
    "ussd_code": "",
    "bank_logo": "",
},
{
    "bank_code": "",
    "cbn_code": "120004",
    "name": "Airtel Smartcash PSB",
    "bank_short_name": "airtel-smartcash-psb-ng",
    "ussd_code": "",
    "bank_logo": "",
},

{
            "bank_code": "090133",
            "cbn_code": "",
            "name": "Al-Barkah MFB",
            "bank_short_name": "",
            "ussd_code": "",
            "logo": "",
        },

"""
